language: scala

scala:
  - 2.11.8
  - 2.12.0

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

after_success:
  - if [[ $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      sh "$TRAVIS_BUILD_DIR/scripts/travis-bintray-credentials.sh";
      sbt ++$TRAVIS_SCALA_VERSION publish;
    fi

